a:4:{s:5:"child";a:1:{s:0:"";a:1:{s:3:"rss";a:1:{i:0;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:1:{s:7:"version";s:3:"2.0";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:1:{s:0:"";a:1:{s:7:"channel";a:1:{i:0;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:3:{s:27:"http://www.w3.org/2005/Atom";a:1:{s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:3:{s:4:"href";s:30:"http://feed.feedsky.com/8_fsep";s:4:"type";s:19:"application/rss+xml";s:3:"rel";s:4:"self";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:37:"http://www.feedsky.com/namespace/feed";a:1:{s:9:"self_link";a:1:{i:0;a:5:{s:4:"data";s:0:"";s:7:"attribs";a:1:{s:0:"";a:2:{s:4:"href";s:30:"http://feed.feedsky.com/8_fsep";s:4:"type";s:19:"application/rss+xml";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:0:"";a:7:{s:13:"lastBuildDate";a:1:{i:0;a:5:{s:4:"data";s:29:"Fri, 25 Jan 2013 12:58:00 GMT";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:12:" [铂程斋]";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:22:"喷嚏网--[铂程斋]";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:47:"http://www.dapenti.com/blog/blog.asp?name=xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:8:"language";a:1:{i:0;a:5:{s:4:"data";s:5:"zh-cn";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:9:"copyright";a:1:{i:0;a:5:{s:4:"data";s:11:"dapenti.com";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"item";a:10:{i:0;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:2:{s:0:"";a:6:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:50:"上访女子被关太平间3年 现身讲述经历";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72570";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1597:"<P>因为对丈夫被劳教的裁决不服，黑龙江伊春市居民陈庆霞长年上访，被当地政府部门劳教18个月，而劳教结束之后，陈庆霞竟然又被有关部门安置在一所废弃的太平间里，长达3年之久，伊春市政府回应称对此事件负有责任，必须认账。 <A href="http://t.cn/zYZZXL8">http://t.cn/zYZZXL8</A> </P>
<P>
<div><object id='sinaplayer' width='480' height='370' ><param name='allowScriptAccess' value='always' /><embed pluginspage='http://www.macromedia.com/go/getflashplayer' src='http://you.video.sina.com.cn/api/sinawebApi/outplayrefer.php/vid=95966114_1_aB7kSyY6XmCP+Eh0HTWxve0D+PcXuvDoj2u9s1WlLAlPE1XaapWca9sB4SjSFqwbrz0xHcZkeP8wkkR5Zas/s.swf' type='application/x-shockwave-flash' name='sinaplayer' allowFullScreen='true' allowScriptAccess='always' width='480' height='370'></embed></object></div>
</P><br><br>打喷嚏链接：<a href='http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72570' target=_blank>http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72570</a>
<br><br>喷嚏图卦微信：penti_tugua
<br><br><IMG style='BORDER-BOTTOM-COLOR: #000000; BORDER-TOP-COLOR: #000000; BORDER-RIGHT-COLOR: #000000; BORDER-LEFT-COLOR: #000000' border=0 src='http://imgs.dapenti.org:88/dapenti/CcMqMpRg/XY6Yw.jpg'>
<br><br>每天网络精华尽在【<a href='http://www.dapenti.com/blog/blog.asp?subjectid=70&name=xilei' target=_blank>喷嚏图卦</a>】&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='http://weibo.com/dapentizk' title='喷嚏网官方新浪围脖' target='_blank'>喷嚏网官方新浪围脖</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 25 Jan 2013 20:58:00 +0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:6:"author";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72570";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:1;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:2:{s:0:"";a:6:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:33:"【段子】鬼子占领钓鱼岛";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72569";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1321:"鬼子占领钓鱼岛，我抗日军民极为愤慨，纷纷拿出绝招欲狠狠打击日本侵略者。嘎子凫水登岛没找到鬼子烟筒；高传宝带民兵挖地道中途漏水；赵庄民兵做的水雷全沉了底；雁翎队顶着芦苇驾船在大海上埋伏，结果直接被鬼子发现了；铁道游击队扒火车还没出境就出了轨。几路抗日人马汇合，最终决定还是回国砸车。(<A class="WB_name S_func3" title=弹弓子c href="http://weibo.com/u/2778484294" usercard="id=2778484294" nick-name="弹弓子c" node-type="feed_list_originNick">@弹弓子c</A>)<br><br>打喷嚏链接：<a href='http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72569' target=_blank>http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72569</a>
<br><br>喷嚏图卦微信：penti_tugua
<br><br><IMG style='BORDER-BOTTOM-COLOR: #000000; BORDER-TOP-COLOR: #000000; BORDER-RIGHT-COLOR: #000000; BORDER-LEFT-COLOR: #000000' border=0 src='http://imgs.dapenti.org:88/dapenti/CcMqMpRg/XY6Yw.jpg'>
<br><br>每天网络精华尽在【<a href='http://www.dapenti.com/blog/blog.asp?subjectid=70&name=xilei' target=_blank>喷嚏图卦</a>】&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='http://weibo.com/dapentizk' title='喷嚏网官方新浪围脖' target='_blank'>喷嚏网官方新浪围脖</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 25 Jan 2013 20:45:00 +0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:6:"author";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72569";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:2;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:2:{s:0:"";a:6:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:30:"媒体札记：“美人计”";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72567";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:31403:"<P>一、定时炸弹</P>
<P>昨天午前，新华社发出快讯，称朝鲜宣布“正计划进行第三次核试验”：“在反美对决战中，朝鲜不掩饰将继续发射卫星和运载火箭，以及进行更高水平核试验以瞄准宿敌美国……六方会谈和‘9&#8226;19’共同声明不再存在，以后不会再有讨论朝鲜半岛无核化对话。”</P>
<P>一边展示那份抨击“安理会成员国像木偶通过决议”的朝鲜国防委员会声明，新浪一边在首页推荐《微博网友速评朝鲜宣布核试验》，所引留言除了来自凤凰卫视评论员李炜的“如果朝鲜进行第三次核试验，中国可能会被激怒”外，就是@胡锡进对半岛问题的长期立场：“理解朝鲜的不安全感，但我依然认为这是个非常愚蠢的决定。金正恩应跳出其父亲的战略思维框架，核武器保护不了朝鲜政权的长期安全。朝鲜只有实现民生的繁荣，才有前途。美日韩总吓唬朝鲜是在恶化半岛局势，如有恶果，韩国必是首食者。”</P>
<P>“它还在声明中还不点名批评中国说：‘连应当带头建立世界公正秩序的大国也被美国的专横和强权所压抑，糊涂得甚至不惜抛弃必须坚持的起码的原则’”——这句晚间留言，更被直接纳入了今日环球时报社评《朝核危机，中国不需看任何一方脸色》。</P>
<P>面对这种“里外不是人”的局面，胡总编只得承认“中国处于严重的两难局面，不仅半岛无核化目标越来越遥远，连在朝鲜同韩日美之间寻求外交平衡也几无可能”，所以，他干脆要向决策者建议“那就由它去”：“中国劝说各方的那些力气，就可以有相当一部分转化成对自己原则框架的保卫……如果朝鲜搞新的核试验或者再发‘卫星’，中国就应毫不犹豫地减少对朝援助。如果韩日美推动安理会对朝鲜采取极端制裁，中国就应坚决制止，迫它们修改草案。”</P>
<P>金正恩翻脸，是因为安理会那份要求朝鲜“不得再使用弹道导弹技术进行发射”的决议。人民日报昨天将这则消息放在了头版，并注明“中方重申应通过对话协商化解矛盾”，按照所引用的中国常驻联合国代表李保东口径，“中方建设性参与了安理会有关磋商，并对刚刚通过的决议投了赞成票。”</P>
<P>可是，一天过去，金正恩的公开声明里已然连“老大哥”艰难维持的六方会谈都弃若敝屣。最高党报只好在《朝鲜称继续进行高水平核试验，中方望保持冷静，俄表示遗憾》的基础上，扳着指头历数自己两年以来的苦口婆心：“《共同努力，促使半岛局势向‘和’迈进》、《重启六方会谈是打破僵局最佳途径》、《‘无条件’（重启六方会谈）就是最大前提条件》、《不要将六方会谈束之高阁》、《重启六方会谈不能一拖再拖》、《朝鲜半岛和平稳定须标本兼治》……这是2011年以来本报关注朝鲜半岛局势的部分‘钟声’文章标题。令人遗憾的是，同时期有关各方的媒体不是探讨如何消除对抗，而是猜测对手在酝酿如何挑衅，鼓动主动出击打压对手。”</P>
<P>再苦口婆心一回吧。奉劝有关各方“真的该打个冷战，清醒清醒头脑”，这篇《半岛局势呼唤智慧和勇气》强调“中国作为一个负责任大国的作为有目共睹，理应得到尊重”，质问“由着性子逞一时之快容易，惹出大麻烦收不了场的结局又将如何处置？”——倒是新华网首页推荐之时，已经不愿再为“小弟”讳，直接将标题里点名批评“由着性子”的就是朝鲜。</P>
<P>东亚局势里还有另一颗定时炸弹，那就是钓鱼岛。</P>
<P>昨天，五大门户曾一度以直播方式播报台湾保钓船凌晨出航计划送妈祖神像上钓鱼岛、遭遇日本拦截之事，水战画面成为新闻首页热门主图。下午16时18分，@胡锡进就是因这张照片而宣布心中“不是滋味”，誓言“总有一天中日会爆发海上‘水炮大战’。中国的军舰也做好准备吧，镇住压住日本的嚣张，军队是最后的筹码”。</P>
<P>可惜，过了不到半个小时，他心里更不是滋味了：“台湾媒体称，这次保钓护渔行动中，有大陆3艘海监船现身，台‘海巡署’为避免引起两岸共同保钓疑虑，竟对大陆公务船‘宣示主权’，并强力要求大陆船离开。台湾兄弟啊，怎么说你们！”</P>
<P>网络编辑们此时已展示《台公务船为避免认为两岸联合保钓，要求大陆海监船离开》的消息，根据环球网所引中央社描述，“10时50分中国大陆的3艘海监船在距钓鱼岛西南西20海里处出现，相对位置在距台湾‘海巡署’‘和星舰’左侧2.5海里。为‘避免引起两岸共同保钓疑虑’，台湾海巡舰艇以广播及LED灯表示‘钓鱼台是中华民国领土，这里是中华民国钓鱼岛海域，请立即离开’。”</P>
<P>于是，难怪环球时报要用另一篇社评来叹息《两岸保钓不协调令日本多份嚣张》：“钓鱼岛原本处于台湾省的行政管辖，大陆全力保卫之，这中间没法直接说出口的含义真是有很多。台湾当局怎么对待大陆的行动，两岸民众都在看着，历史也将以公平的态度予以记述。”</P>
<P>不过，正如环球网首页转发时将标题改为“日本有本事冲中国大陆来别欺负台湾保钓船”所示，这份人民日报子报还是要有大哥气量：“两岸都是中国人，保钓不计贡献大小。台湾当局拨拉小算盘，我们也权装看不见。中国大陆将担负起保卫钓鱼岛的重任，中国大陆和日本的冲突已是钓鱼岛争端的绝对‘正面战场’。日本有什么本事，都请冲着中国大陆来。8艘巡逻艇围着欺负弱小的台湾保钓船，这样的表演代表不了你们的强大。”</P>
<P>倒是凤凰网最难将息，除了贴出《独家视频：台保钓船遭日舰水炮喷射，甲板满是碎片》》，还要在子夜一点转发自家卫视新闻节目，由中华保钓协会秘书长黄锡麟批评“台湾海巡署设备、装备差那么多……两岸之间合起来有什么错呢？把钓鱼台(岛)拿回来有什么错呢？”</P>
<P>《“全家福”号保钓人士黄锡麟：“两岸应誓死保钓，共享资源”》——东方早报也是以这样一个标题概括世界华人保钓联盟对“大陆海监船的驰援表示感谢”的态度。版面上，“台保钓船遭日方水炮射击”的前半句就是“日本公明党党首今或见习近平”，除了播报这一信号，门户更用首页标题发掘出以下细节：“日本防卫省统合幕僚监部昨天还公布数据称，在截至2012年12月末的9个月里，航空自卫队战斗机紧急升空应对中国飞机的次数已达160次，超过历史最高纪录。”</P>
<P>只是，重庆晨报总要厌弃——《信还没送到，又开水炮打保钓船，日本缺诚意，送信不如言而有信》。午前，新华社发出最新消息，总书记终于见了东瀛信使，五大门户迅即更新头条，凤凰网补充：“山口向习近平转交了日本首相安倍晋三的亲笔信”。</P>
<P>二、重庆清洗</P>
<P>另一颗定时炸弹也在昨夜终于引爆。而且，这一炮霎时压过外交争端，成为新浪搜狐网易腾讯凤凰网不二头条，直至今日上午。</P>
<P>导火索前天就已点燃。事实上，如果不是南方都市报周三刊出那篇《色诱政企要员，雷政富之后的重庆“性爱视频”敲诈系列案》，很难说这颗定时炸弹还会埋藏多久。</P>
<P>“在1月21日晚播出的东方卫视‘东方直播室’栏目中，雷政富不雅视频爆料人朱瑞峰当场展示了一张光碟，据称其中还有另外4名尚未曝光官员的不雅视频。而据南都记者了解，除雷政富外，至少5名政企要员牵涉‘性爱视频’”——用这段消息配上习近平坚持“老虎”、“苍蝇”一起打的指示，本期深度周刊封面上是一个被女子双手环抱的剪影。</P>
<P>内版漫画的色诱意味更加明确，是一位男士叼着雪茄坐在女性张开的双腿下。记者张书舟署名，从那永煌集团网站的开开关关说起，“去年11月，雷政富与女子赵红霞的性爱视频在网络上曝光，这段拍摄于2008年初的视频很快就让时任重庆北碚区委书记的雷政富被双规。永煌公司的创始人肖烨、严鹏等人，正是这段视频的拍摄者，他们操纵赵红霞等女员工色诱重庆本地官员发生关系并偷拍下性爱视频以之要挟。在北碚区委书记任上落马的雷政富只是其中一个被拍下视频的官员。”</P>
<P>因“雷冠希12秒”而走红的肖红霞，被报道是偷拍视频的任务执行者，同时也是肖烨的情人，她和另外两名女子根据一份肖提供的重庆政府官员通讯录，依次发送手机短信及照片挑逗，直至“关系到位”相约酒店开房，“视频得手后，如果不够清晰，肖烨会要求和官员开房再录一次，如果视频清晰、完整达到他的要求，他们就会安排在下一次开房时捉奸。”</P>
<P>按照报道中引用的知情人描述，捉奸过程如下：“当官员和肖烨派遣的女子进入房间后，严鹏、王建军等人会选择时机敲门，进入房间后王建军以女子男朋友的身份暴怒，负责跟踪开房过程的严鹏自称的身份则是私家侦探，还有另外一名许姓男子自称黑社会组织成员，他们会以‘睡了我老婆’为名对官员进行殴打，并拿出偷拍的性爱视频作为证据播放给官员本人看。有知情人称，雷政富没看到视频前还曾猛烈还击。在看到被偷拍的视频后，官员就会要求和解，此时王建军等人就打电话找‘大哥’肖烨来处理此事。肖烨到场后，先与官员单独交谈，之后就会安抚官员并保证‘处理好视频’，斡旋之后即让官员离去。”</P>
<P>感叹“引诱－偷拍－捉奸”的“仙人跳”把戏老套，南都记者接下来就公布了自己掌握的证据，除雷政富实名外，其余5人以字母代替：“时任重庆市某区常务副区长的F官员，2008年8月与赵红霞在渝通宾馆开房时被偷拍，2008年11月在同一宾馆与赵红霞开房时被捉奸。时任重庆市政府某办公室主任的L官员，2008年初分别与赵红霞和张丹在果岭时尚酒店开房，被赵红霞偷拍，一个月后在同一酒店与赵红霞开房时被捉奸。时任重庆某区区长的H官员，与赵红霞在重庆金源酒店开房时被偷拍，与谭琳在同一酒店开房时被捉奸。时任重庆市城投控股的某上市地产公司S董事长，2008年3月在重庆东和花园酒店与赵红霞开房时被偷拍，2008年4月与赵红霞在同一酒店开房时被捉奸。时任重庆市某委员会主任的P官员，2008年9月与赵红霞开房时被偷拍，2009年2月与赵红霞在小天鹅宾馆开房时被捉奸。”</P>
<P>就这样，肖烨成功了。根据这篇报道，雷政富主政的北碚成为永煌华丽转身的起点，在其他几名被肖烨等人偷拍到视频的官员主政之地，永煌集团也获得了少则百万，多则千万的市政工程项目。</P>
<P>而被偷拍捉奸的人，居然，也成功了。以“反常”为题，南方都市报终于将话题引向重庆昔日主宰者：“雷政富因被肖烨等人持视频威胁，自知终将事发，于是主动向时任重庆主要领导坦白了此事，重庆市公安局原局长王立军负责处理此案……根据公开资料，在2009年11月警方侦破此案后，前述6名官员、高管的仕途并未受到影响，不少人还获得了升迁。”</P>
<P>毫无疑问，这理应是篇足以轰动全国的新闻，可与此前南方系同胞兄弟南都周刊《起底王立军》媲美。但是，张书舟没能成功。当期深度周刊在当日南方都市报电子版上仅有短暂停留，清早就已撤除。</P>
<P>私下复制传播在微博论坛中进行——直至昨天上午一份“优化版”的出现。虽系对南都报道的转载摘录，但原本用来隐去官员姓名的字母都被替换成了具体的名字：F官员、L官员、H官员、S董事长、P官员分别对应范明文、罗广、韩树明、粟志光、彭智勇。</P>
<P>虽然这条长微博很快被删除，但重庆主事者此时应该也明白，事已至此，只有和盘托出。</P>
<P>昨晚20时41分，@重庆市人民政府新闻办公室发布《重庆破获一敲诈勒索团伙，涉案违纪公职人员被免职》：“从有关部门获悉：2012年11月20日以来，重庆市纪委在对雷政富违纪违法问题深入调查中，发现一个进行敲诈勒索犯罪团伙的线索。经公安机关侦查，2008年至2009年期间，肖烨等人采取色情勾引、秘拍不雅视频等手段，敲诈数名党政干部和国有企业负责人。目前，重庆市委已对被敲诈违纪人员予以免职，并将根据调查情况依法依纪严肃处理。检察机关已批准逮捕肖烨等犯罪嫌疑人。”</P>
<P>20分钟后，是以中共重庆市委和国资委名义发布的两份具体任免决定，不只5人，合计10人：彭智勇、范明文、韩树明、艾东、罗登友、谢华骏、周天云、何玉柏、罗广西、粟志光均被免职，从区委书记、县委书记到国企董事长之职。</P>
<P>在这20分钟里，所有的时事媒体账号都已围拢过来，全力转发。而@南都深度，理所当然是其中最耀眼的主角。在重庆官方公布10人名单之后2分钟，这个代表南方都市报深度新闻部的账号，就已自豪地发布“独家消息预告”。</P>
<P>独家消息就是一天前被雪藏的张书舟报道《重庆五要员和雷政富一同落入桃色陷阱》，再辅以旧闻对照：“2010年1月16日，薄熙来说：‘我们有份特别的责任，要把下一代培养好，让你们德智体全面发展，就像你们的教委主任彭智勇，智勇双全，还要加上德。’”</P>
<P>一晚上发了13条微博，直到把聚光灯投射在“11”这个落马者总数上、用“把权力关进笼子，离不开媒体监督”道晚安。总结的任务已由@南都评论的同事代劳：“这一次，纪委又远远落在了媒体后面。重庆警方早于2009年即侦破偷拍视频案件，但涉案官员和国企高管不但未受处理，反而稳坐高位甚至继续高升，显示当地官场已然失范，警方亦为少数人控制并用于非正常用途。此番媒体报道一天之后，市委宣布处理结果，难脱被倒逼的嫌疑，当然，为时虽晚，也算亡羊补牢。”</P>
<P>作为报社官方微博，@南方都市报当然与有荣焉。除了暗讽一句“官方反应很快嘛”，还要感叹“这些人的名字终于不用再打马赛克了”。是的，周三的电子版已经找回了深度周刊，而且，像是补偿，那个色诱版面图样今晨重现于南方都市报纸面，“敲诈手法曝光：引诱-偷拍-捉奸”的段落也复登一次。《南都查实其中五官员遭色诱过程》里，更摘录网友@六十还童的追问：“我要追问的是，前几年重庆打黑如此严厉，肖烨为何没被打？去年薄王倒台后，这宗案件为何没被追查？案情早已水落石出，雷政富被曝光后，为何又拖了好几个月才处理？重庆还有多少案件还没曝光？”</P>
<P>作为主稿的那篇《重庆十名政企要员涉不雅视频被免职》，引自新华社，事实上，就是@新华社中国网事，昨晚不仅发出了那10个人的头像拼图，并第一个明确写出“此批官员免职原因系涉及不雅视频”。</P>
<P>另有两段@新华视点发出的微评，也为门户今晨重点推荐：“按重庆方面的说法，雷政富等人是被一个以色情利诱、秘拍不雅视频的犯罪团伙敲诈了。违纪官员被处理，犯罪团伙被批捕，似乎应值得高兴，可总让人感觉不对劲。苍蝇不盯无缝的蛋，但凡官员洁身自好，有关部门监督有力，雷等人怎么会受害呢？”；“为何众多官员糖衣炮弹一打就中，纷纷堕入色诱圈套？倘无网络爆料、媒体追问，包括雷政富在内的这些官员会被处理吗？永煌集团凭美人计迅速做大，是否说明地方市政工程承包也太随意？”</P>
<P>《重庆竟还有10个“雷政富”，全部免职》、《1个雷政富倒下了，10个“雷政富”牵出来》——新闻晨报和大河报所见略同；海南特区报在封面放上一段身材姣好的女性剪影，称重庆10官员、国企主管乃是中了“美人计”；现代快报和东方卫报同城相约，将这些被色诱者的尊容放大呈现在头版；东方卫视子午线节目联想起衣俊卿，创造新名词“顶风做爱”……只有重庆各报保持一致，将三份通告原文置于内版。</P>
<P>中国青年报同样大段引用了南方都市报前天的调查报道，但也有独家内容，即门户首页推荐时所概括的“多人本前途远大”。根据此文，“最令人意外的落马官员”是九龙坡区区委书记彭智勇，这位“内有灵魂”的“坡民”书记成不雅视频主角后，很多网民表示难以置信，因为“那么儒雅帅气的人，怎么会犯这种错误？”；另一位就是刚40岁出头就出任重庆市石柱县县长的艾东，“因为有多年秘书工作经历，艾东与很多官员的‘霸气’相比，显得相对内敛、儒雅、温和。正因为此，很多市民对他牵涉不雅视频感到难以置信。”</P>
<P>人民日报发了简讯，不过，其子报环球时报不会这么低调，刊出大概又是全国独一份的评论。《惩治色诱与贪官，重塑司法正义》里，作者刘继忠先行介绍了“网民五味并存的激烈反响”，即“有要严惩肖烨的，也有替肖烨打抱不平的，也有借此诅咒贪官的”，而后宣布“这背后隐藏着依然是对贪官民粹式的社会戾气”：“一股是看得见民粹主义者的喧嚣，他们极力替违法者辩护，期望减轻其罪责，另一股是看不见的更可怕声音：官员群体的幕后施压，期望杀一儆百。这两股声音都力图以错误手段惩罚犯错者，使之陷入冤冤相报的逻辑圈套。”</P>
<P>微博论坛上确实反响激烈。和网络编辑热烈展示的方向一致，“6人先后与同一女子开房”、“薄熙来知情后封存，数名涉案者案发后获升迁”这两个细节也是人们讨论的重点。新浪微博已将“反腐奇女子赵红霞”作为热门话题推荐在页面顶端：@雾满拦江诗心大发，“飒爽英姿五尺枪，、曙光初照演兵场。中华女子多骑志，领导脱得精光光”；@青媒素高歌一曲，“日过红霞官帽飞，领导打靶被双归，被双归”；@金一宁对比讽刺，“重庆的百姓都在唱红歌的时候，重庆的官员们都在睡红霞”；@张泉灵以一个女人的身份留言：“我特想知道，有没有肖烨设局，然后被人拒绝、不接招、不成功的案例？”</P>
<P>@财经网不愧是媒体账号翘楚。昨夜微叹《当今部分官员之猥琐已到震古铄今地步》，“6位直辖市属高官所上床的对象竟是同一位女子。所谓衣冠禽兽，说的正是这样的一群”；再有微数据：“阵容强大，整整一个男子足球队。”</P>
<P>三、户口问题</P>
<P>《雷政富的桃色新闻终于没烂尾》——这是长株潭报仅有的欣慰。</P>
<P>不过，仍在苦等下文的多的是。响应新华社5天前的率先开炮，钱江晚报今天也来汇报自己连线广州市越秀区、陕西省安监局、山西省监察厅“打了近十通电话只得到一个结果”的战况，并得新浪扩散：“追访飞机上打人的方大国、表哥‘杨达才’以及山西苯胺泄露事故的进展，不想这些曾在事件初始作出相关回应的部门，给记者上了一门生动的推诿交流课，‘不归我们管’、‘我不了解’、‘我是新来的’，推诿之词可谓花样迭出。”</P>
<P>长江日报告诫《《别让“烂尾新闻”寒了公众的心》——其实，长江后浪推前浪，倒也不必花费太多心思回顾丑闻，眼前的事都已经快忙不过来了。</P>
<P>以今晨门户首页所示为据，在《王岐山：拉长耳朵瞪大眼睛盯住顶风违纪典型》下面，就有《李春城妻子被曝任红会领导时两月去单位一趟》、《浙江5人疑坐冤狱17年续：1人称难忍刑讯咬断舌头》、《商丘官员曝艳照被刑拘，长期玩弄女性拥多房产》、《深圳“20亿村官”被移送司法，曾称遭人污蔑》……</P>
<P>各级官方也在忙着回应，可惜得到的反馈多是“不相信”。</P>
<P>据中新社报道，针对此前央广所报“黑龙江伊春上访女子陈庆霞被关废弃太平间三年”之事，伊春市带岭区宣传部回应称称这是对信访人员的“人文关怀”。于是，新京报立刻还以反问——《上访者被关三年是“人文关怀”？》，更获新浪腾讯凤凰共同助力。</P>
<P>而就在陈庆霞那两扇贴满“我告饶了”的窗户下面，中国青年报又从东北带回了《辽宁东港80后副市长履历造假疑云》，虽然人民日报为此已连出了两期澄清稿，但异议者又从中找到了“‘非中共党员’的董海涛曾担任一高校部门的党支部书记”的蹊跷，以至于丹东市委组织部外宣办工作人员只能回一句：“难道网上的质疑都要去理会吗？”</P>
<P>相较而言，济南市公安局昨天通过微博为历城区原公安分局局长程绍春所作的辟谣已经算是成功的了。根据“网传的小区非程绍春个人拥有，而是历城公安分局民警宿舍”之声明，法制日报今晨发布实地探访所获：“一位知情人士告诉记者，网上流传的说法很有可能是造谣……由于该小区楼房有不少警察出资购买，有上访户为引起社会关注，便把警苑小区给‘裹挟’了进来。”</P>
<P>但那些相信“谣言”胜过“辟谣”的人们想必会反唇相讥，“就算‘房祖宗’有假，那‘房姐’总是真的吧？”</P>
<P>的确，陕西神木县农村商业银行原副行长龚爱爱的“房姐”连续剧，大有与此前郑州“房妹”争艳之势。再加上山西运城的“房媳”，她们最大的共同点就是都拥有多个户口，而这也正是舆论最为关注之处。中国户籍制度管理关联重要福利，素有严格之名，甚至屡被抨击死板僵硬，可如今恍然发现，原来有那么多“暗渡陈仓”者，这怎不叫那些民间意见领袖忿忿不平？</P>
<P>除了由时评作者佘宗明写出《户口是“房氏家族”的寻租代码》，潇湘晨报还通过《户口疑云：房姐爱，涉腐官员也爱》列明针对龚爱爱的四点困惑：“无此人也能补录出户口”；“不存在的地址也能迁入户口”；“为何有在北京出生才有的号码”；“有关部门到底急着掩盖什么”。而后，这份湖南报纸又列举安徽凤阳县原公安局长陶勇、广东汕尾原烟草局长陈文铸等其它一些拥有多户口的贪官，并摘录早前广州日报所言：“从中纪委透露的少数官员秘密取得双重国籍，到不时冒出的官员双重户口，给反腐败提出了严峻的挑战。即便是现下呼声很高的官员财产公开，倘若有了双重户口的掩饰，那公开的意义多少会打折。因而，堵死官员的双重身份漏洞，既是反腐败的需要，也是支撑户籍改革的最起码条件。建议不妨把摸查官员的双重身份作为反腐的一个重要内容。”</P>
<P>今天，在鼓励《从“抽查”起步，迈向官员财产公开》的版面下方，这份广州市委机关报又由作者汤嘉琛再说一遍“惩治违规户口要拿出反腐决心”。京华时报亦有头条评论《房多多户多多，漏洞为何那么多》，魏英杰有言：“变造或骗领居民身份证等违法行为均有明文规定，对构成犯罪的将依法追究刑事责任。为何这些当事人（包括派出所民警）敢于冒风险办理多个户口？这一方面说明其中利益诱惑巨大，另一方面或许也表明，相关制度设计仍不够严密，违法成本仍不够高。”</P>
<P>被凤凰网推荐的还有南方都市报的《户籍改革并非只为抑制“房氏家族”》：“当前尚不明了‘房氏家族’是以何种途径越过制度障碍，一个可以明确的事实是，如果户籍制度出现漏洞，经济适用房规则，大城市的房产限购政策等，都将导致不公平现象……官员存在突破制度障碍的便利，普通民众却难免要顺应规则，因为兰考事件，孤儿落户难问题走进我们的视线，在此之前，围绕准生证话题，民众也曾对户籍制度持续吐槽。凡此种种，不难看出改革此制度应有的方向，即不能停留于户籍制度改良，而要彻底改革户籍制度，代之以普遍的平权和科学的社会管理。”</P>
<P>同样将这一话题提升到制度改革的还有东方早报。在通报《公安部欢迎微博举报问题户口》之后，由杨耕身强调《严查“狡兔三户”不能强化户籍不公》：“‘狡兔三房’的现状，无疑正是一些特权者对户籍福利最大化利用的结果……只有在一个开放而平等的社会，在一种祛除了附着于户籍之上大量隐性福利的制度设计之下，特权者才不再能够对户籍福利‘念念不忘’。如果不公正的户籍制度反而借种种乱象进一步强化，那么这样的现状除了使户籍制度因其愈发严苛而附着更大的利益，并令普通民众进一步被排斥于公平的社会管理之外，并不能带来实质性改变。”</P>
<P>《狡兔三窟，贪官多户》——腾讯也在首页专题中以这句成语为喻。承认“表面上，户口、特别北京户口确实难办”，但责编张春续要告诉各位，“居民身份管理存漏洞，使得贪官的假户口拿得易、用得顺”：“根据北京青年报的记者调查，在北京甚至存在着不少‘户口代办公司’。这些公司多数都宣称他们可以通过‘关系’代办一个北京户口（也就是把户口从外地迁入北京），当事人需要为此花费6万元左右。而如果想要‘双重身份’，新建一个北京户口则需要10万元左右。虽然这类‘代办公司’鱼龙混杂，所言未必属实。但在许多专业人士看来，办理虚假户口已经形成了一条利益链确是毋庸置疑的……人徇私枉法和不作为是问题的一方面，另一方面就是户籍系统的落后，使得假户口难以查证……不同行政区域和不同户籍管理系统之间也存在着信息壁垒，对查处跨行政区的‘一人多户’造成了很大的困难”。</P>
<P>“可见，对那些贪官污吏们来说，户籍制度非但不恶，反倒是保护伞和福利。这也难怪，时至今日户籍制度改革仍推进乏力”——结语下方，是这家门户网站请各位决定新闻立场，午前结果显示，99%的投票者支持对官员户籍信息展开普查。</P>
<P>中央喉舌似乎对户口买卖勾当也不知情。央视新闻1+1里，董倩瞪大双眼惊呼《他们的户口，他们的房！》，人民日报今晨更是将《公安部调查陕西“房姐”多个户口》放在了头版，并转发广州日报前天那篇《“房姐”背后藏着多少老虎苍蝇》。</P>
<P>老虎苍蝇确实多。虽然昨晚麦田房产通过官方微博宣称“8套政府优质资源”一说实为经纪人急于成交而编造的不实信息，但21世纪网此时已经呈上了《官员抛房必备读本》，引用律师们对“交易是否属于销赃行为”、“是否有法律风险”的解读，最后送上一句“祝你好运”。</P>
<P>由其最新发布的《沪公务员直降百万抛豪宅，买家或钱房两空》更是乘胜追击，再获门户热荐。核心提示如下：“‘公务员急着将豪宅脱手，一定是觉得最近有被查的可能，’据沪上一位房产经纪人介绍，这种房子交易风险很大，买房过程中国家可能随时冻结公务员资产，买家将钱房两空。”</P>
<P>“反腐风紧时，便釜底抽薪连夜抛售豪宅，大不了走为上，携款出逃”——虽然根据央广午时报道，中纪委已否认曾向中央通报国内豪宅抛售风潮，但新浪专题《官员“房事”三十六计》已经想像画面，并据此期待官员财产公开制度化。</P>
<P>似乎只能指望这个笼子了。只不过，由鄢烈山在专栏里反问一声“官员财产公开为何要等上面‘通知’”之余，南方都市报也要降低期待值，用一个通版带来珠海市委副书记、市纪委书记王衍诗的体会——《财产公示既不是洪水猛兽，也不是灵丹妙药，副科长以上实职领导干部家庭财产情况已内部公示近4个月》：“财产公示只是众多反腐手段中的一种，它发挥作用是有条件的，起到的作用也是有限的，不能神化它，更不能天真地认为一公示就可消除腐败。”</P>
<P>况且，南方日报今天又转达了省人大代表叶鹏智对官员隐私权的坚持。他建议随机抽检，并称“可以向组织申报财产，但不一定对公众公开……要警惕一些人打着‘民意’的旗号搞民粹主义”。面对此稿，搜狐网易和凤凰网选择其中“广东代表称官员不是老百姓奴隶，财产属于隐私”之意作为标题推荐在首页，还是南粤出身的腾讯厚道，只言“人大代表：建议用‘摇号’办法搞官员财产公开”。</P>
<P>&nbsp;</P>
<P>来源：FT中文网 徐达内</P>
<P>链接：<A href="http://www.ftchinese.com/story/001048690?full=y">http://www.ftchinese.com/story/001048690?full=y</A></P><br><br>打喷嚏链接：<a href='http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72567' target=_blank>http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72567</a>
<br><br>喷嚏图卦微信：penti_tugua
<br><br><IMG style='BORDER-BOTTOM-COLOR: #000000; BORDER-TOP-COLOR: #000000; BORDER-RIGHT-COLOR: #000000; BORDER-LEFT-COLOR: #000000' border=0 src='http://imgs.dapenti.org:88/dapenti/CcMqMpRg/XY6Yw.jpg'>
<br><br>每天网络精华尽在【<a href='http://www.dapenti.com/blog/blog.asp?subjectid=70&name=xilei' target=_blank>喷嚏图卦</a>】&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='http://weibo.com/dapentizk' title='喷嚏网官方新浪围脖' target='_blank'>喷嚏网官方新浪围脖</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 25 Jan 2013 19:40:00 +0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:6:"author";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72567";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:3;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:2:{s:0:"";a:6:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:41:"【喷嚏】新史记 名伶传 赵红霞";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72566";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1127:"【新史记 名伶传 赵红霞】赵红霞者，巴山人氏，生得远山眉黛、细柳腰肢、娇美可怜!霞，烈女也，不惜名节，商贾肖助其铲奸除恶。河蟹3年，霞纤手抱肥躯，娇喘斗贪官，12秒挑雷知府于马下，云雨床第之术为万民所赞叹！后数年，又恶斗十知府。复兴元年，十墨吏锒铛入狱，另二十官待查，霞之功也。<br><br>打喷嚏链接：<a href='http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72566' target=_blank>http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72566</a>
<br><br>喷嚏图卦微信：penti_tugua
<br><br><IMG style='BORDER-BOTTOM-COLOR: #000000; BORDER-TOP-COLOR: #000000; BORDER-RIGHT-COLOR: #000000; BORDER-LEFT-COLOR: #000000' border=0 src='http://imgs.dapenti.org:88/dapenti/CcMqMpRg/XY6Yw.jpg'>
<br><br>每天网络精华尽在【<a href='http://www.dapenti.com/blog/blog.asp?subjectid=70&name=xilei' target=_blank>喷嚏图卦</a>】&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='http://weibo.com/dapentizk' title='喷嚏网官方新浪围脖' target='_blank'>喷嚏网官方新浪围脖</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 25 Jan 2013 18:53:00 +0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:6:"author";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72566";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:4;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:2:{s:0:"";a:6:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:18:"【段子】诺言";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72565";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1336:"拥挤不堪的公交车上，年轻男孩紧紧的搂着才下班的女友在耳边承诺：＂现在的你肯跟着我一起挤公交，委屈你了，以后我一定让你坐上我的车接你下班回家。＂三年后，同样的地点，女孩感动的望着驾驶座上那个言出必行曾对自己许下承诺的男孩，他通过三年的努力，终于成为了这班公交车的司机。（<A class="WB_name S_func3" title=硬邦邦帮主胡子 href="http://weibo.com/thehuzibeer" usercard="id=1320344173" nick-name="硬邦邦帮主胡子" node-type="feed_list_originNick">@硬邦邦帮主胡子</A>）<br><br>打喷嚏链接：<a href='http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72565' target=_blank>http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72565</a>
<br><br>喷嚏图卦微信：penti_tugua
<br><br><IMG style='BORDER-BOTTOM-COLOR: #000000; BORDER-TOP-COLOR: #000000; BORDER-RIGHT-COLOR: #000000; BORDER-LEFT-COLOR: #000000' border=0 src='http://imgs.dapenti.org:88/dapenti/CcMqMpRg/XY6Yw.jpg'>
<br><br>每天网络精华尽在【<a href='http://www.dapenti.com/blog/blog.asp?subjectid=70&name=xilei' target=_blank>喷嚏图卦</a>】&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='http://weibo.com/dapentizk' title='喷嚏网官方新浪围脖' target='_blank'>喷嚏网官方新浪围脖</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 25 Jan 2013 18:13:00 +0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:6:"author";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72565";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:5;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:2:{s:0:"";a:6:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:35:"十号线二期 之 元首的愤怒";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72564";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1027:"<P><EMBED height=400 type=application/x-shockwave-flash width=480 src=http://www.tudou.com/v/KHvaUzdVjq8/&amp;resourceId=0_05_02_99&amp;autoPlay=false/v.swf wmode="opaque" allowfullscreen="true" allowscriptaccess="always"></EMBED> </P>
<P>链接：<A href="http://t.cn/zjkYRCz">http://t.cn/zjkYRCz</A></P><br><br>打喷嚏链接：<a href='http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72564' target=_blank>http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72564</a>
<br><br>喷嚏图卦微信：penti_tugua
<br><br><IMG style='BORDER-BOTTOM-COLOR: #000000; BORDER-TOP-COLOR: #000000; BORDER-RIGHT-COLOR: #000000; BORDER-LEFT-COLOR: #000000' border=0 src='http://imgs.dapenti.org:88/dapenti/CcMqMpRg/XY6Yw.jpg'>
<br><br>每天网络精华尽在【<a href='http://www.dapenti.com/blog/blog.asp?subjectid=70&name=xilei' target=_blank>喷嚏图卦</a>】&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='http://weibo.com/dapentizk' title='喷嚏网官方新浪围脖' target='_blank'>喷嚏网官方新浪围脖</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 25 Jan 2013 18:01:00 +0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:6:"author";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72564";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:6;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:2:{s:0:"";a:6:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:36:"7个月宝宝大跳《江南Style》";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72558";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1364:"<P>
<DIV>
<OBJECT id=sinaplayer width=480 height=370><PARAM NAME="allowScriptAccess" VALUE="always">
<embed pluginspage='http://www.macromedia.com/go/getflashplayer' src='http://you.video.sina.com.cn/api/sinawebApi/outplayrefer.php/vid=95931565_2397059874_a0OySiFrXG7K+l1lHz2stqkP7KQNt6nnimOzu1etLQldQ0/XM5GQZ9QE4SzQBdkEqDhATZ02dv8j0Rg/s.swf' type='application/x-shockwave-flash' name='sinaplayer' allowFullScreen='true' allowScriptAccess='always' width='480' height='370'></embed></OBJECT></DIV>
<P></P>
<P>链接：<A href="http://video.sina.com.cn/v/b/95931565-2397059874.html">http://video.sina.com.cn/v/b/95931565-2397059874.html</A></P><br><br>打喷嚏链接：<a href='http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72558' target=_blank>http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72558</a>
<br><br>喷嚏图卦微信：penti_tugua
<br><br><IMG style='BORDER-BOTTOM-COLOR: #000000; BORDER-TOP-COLOR: #000000; BORDER-RIGHT-COLOR: #000000; BORDER-LEFT-COLOR: #000000' border=0 src='http://imgs.dapenti.org:88/dapenti/CcMqMpRg/XY6Yw.jpg'>
<br><br>每天网络精华尽在【<a href='http://www.dapenti.com/blog/blog.asp?subjectid=70&name=xilei' target=_blank>喷嚏图卦</a>】&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='http://weibo.com/dapentizk' title='喷嚏网官方新浪围脖' target='_blank'>喷嚏网官方新浪围脖</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 25 Jan 2013 16:10:00 +0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:6:"author";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72558";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:7;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:2:{s:0:"";a:6:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:12:"我的同桌";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72557";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:7416:"<P>说这事的时候，已经是小学三年级。 
<P class=MsoNormal>三年级已经记事，记住了就跟随我一辈子。</P>
<P class=MsoNormal>那个时候学校穷，没有桌椅，一块长长的木板就是桌子，垒了几层土坯，少了两层的，能坐下的就是一个长长的木板，桌子是木板，椅子还是木板，很长很长，七八人共用长长的桌子和椅子。</P>
<P class=MsoNormal>房子也是土坯房，刻着岁月和时光。房子不稳，用了一个大人能抱得住的木柱子，顶住已经歪邪的墙。</P>
<P class=MsoNormal>柱子如西西弗斯，房子如西西弗斯推着的大石头，感觉房子不断地告诉我，我要倒了。</P>
<P class=MsoNormal>学校往山坡上走一百五十米，就是冒着浓烟的火车，很气愤地跑着，叫着。</P>
<P class=MsoNormal>老师上课的声音与火车的声音打架，最后火车总赢，于是老师不得不停下来，等火车走。</P>
<P class=MsoNormal>坐在我身边的同学姓高，留着张艺谋拍摄的电影《我的父亲母亲》里男主人公式的小分头。那头，不是老师头，是学生头，是特殊身份。他穿着黑衣服，上下都是黑的，脸却白。黑衣服白脸，是他给我的第一印象。</P>
<P class=MsoNormal>高同学坐不爱说话，比女孩子还静。默默写字，默默地读书，书的内容不记得，就记得都在读，只是声音比别人小。</P>
<P class=MsoNormal>时间也巧，新来了女语文老师，我也是新转学来的，才上了不几天课。</P>
<P class=MsoNormal>有一次，新语文老师提问到了他，他悄悄地站起来，莫名其妙着，看着老师，等着老师说什么，老师不说，看着他，他就慢慢低下头，看看大家，大家看看他。在此之前，他从来没有被老师提问过，尽管他总有被老师提问的渴望。</P>
<P class=MsoNormal>此时，你总会感受到他透到骨子里的忧伤，那种忧伤会传染，传染到爆炸。</P>
<P class=MsoNormal>老师说，高同学，请读课文。</P>
<P class=MsoNormal>于是他读，读着读着，声音就小了，最后蚊子叫。</P>
<P class=MsoNormal>我听着他的心在跳，他的心在发出声音，读书的音符变成了心的颤抖。</P>
<P class=MsoNormal>最后同学们大笑，他哭了。</P>
<P class=MsoNormal>她不知道她的学生为什么笑，他为什么哭。</P>
<P class=MsoNormal>老师有点恼火，想发作，一个同学大声说：“老师，他是地主崽子！”</P>
<P class=MsoNormal>老师和蔼的脸一下子变得政治起来，声音变成了帕瓦罗蒂：“坐下！”</P>
<P class=MsoNormal>那天晚些时候我才知道，这是我的同学一生中惟一被老师提问，第一次读课文。那一天我没有想到，这也是他最后一次读课文，因为是新老师，新老师点到了他，这一点，给他生，也给了他死。</P>
<P class=MsoNormal>下课了，同学们疯着挤着，出来玩。</P>
<P class=MsoNormal>玩的游戏就是把高同学拉到外面，用各种各样的方式踢他、踹他，向他身上吐口水，用各种语言污辱他，因为他是地主的崽子。这一刻，他不哭，倒了，再起来，再倒，再起来，再倒，于是他不起来，坐等上课的铃声。其它的同学看着，乐着，拍着手，高喊着口号，打倒地主。</P>
<P class=MsoNormal>没有同学敢帮他，因为他是地主崽子。</P>
<P class=MsoNormal>斗地主我看过，斗党内走资本主义当权派我也看过，他们这些人白天从家里拉出来，扔到大卡车上，一个村一个村地游斗，被游斗的人脑袋上顶着一个高高的帽子，写着字。有的时候晚上他们也被叫出，开批斗会，全村人都得去，不去不行，不去就没有政治觉悟。偶有地主不服，嘴里嘟囔几句，几个民兵跳出来，上去就打，一直打得对方流血告饶。小孩子们都看，吓得不敢作声，胆子小的，早扑到父母的怀里。</P>
<P class=MsoNormal>那个年代农村的快乐就是斗破鞋，男的女的脖子上挂着两只鞋，一边一只，脸上写着“破鞋”两个字。搞破鞋的人脸上也没有被批斗的感觉，有时还和下面批斗的人互动一下。批斗的人大声问：“搞破鞋好玩吗？”被批斗的人就会说：“有玩”。车上车下哄堂大笑。</P>
<P class=MsoNormal>当时小，听不懂。</P>
<P class=MsoNormal>斗地主崽子，就是跟大人们学来的。 </P>
<P class=MsoNormal>那天上课，他默默地走进屋，走到他的座位上，擦了擦脸上的血。我看着他，他也看着我，我不说话，他也不说话，他不敢和我说话，我也不敢和他说话，但他的恐惧还是传给了我。</P>
<P class=MsoNormal>到了放学的时候，我看着他收拾书包，书包很破。他把书装进书包，所有的书都装进书包，连纸片都没剩，整整齐齐地。他好象要把他读书的空气也要装进去。</P>
<P class=MsoNormal>我禁不住好奇，悄悄地问：“明天还来，为什么要收拾那么干净？”，他也悄悄地说：“不来了，自己学吧。我还得照顾爸爸妈妈。”</P>
<P class=MsoNormal>“那你永远不来了？”我问。</P>
<P class=MsoNormal>“不知道，也可能永远。”他说：“爸爸妈妈在家批斗的时候被打伤，我得回家给他们作饭。”</P>
<P class=MsoNormal>“我告诉你一个秘密，我父亲也被批斗，因为是走资派。”我说。</P>
<P class=MsoNormal>“怪不得你和他们不一样，他们打我，你从来不打我，我早就把你当我的朋友了，可我不敢说。”他说。</P>
<P class=MsoNormal>“那我们就是朋友了。”我说。可手一直不敢伸出去，怕被人看见。</P>
<P class=MsoNormal>在那天稍晚些时候放学，我们分手了，没告别，没说再见，因为知道会再见。</P>
<P class=MsoNormal>第二天，高同学没来，第三天没来，第四天没来，最后听到了他的噩耗。</P>
<P class=MsoNormal>他跟他叔叔上山崩石头，一个哑炮，他叔叔去看了，他也去看了，搬开了压在哑炮的石头，哑炮炸了。</P>
<P class=MsoNormal>他和他叔身子炸没了，炸成了遍地的带血的肉块。</P>
<P class=MsoNormal>就在那一天，我找了一个地方，默默地哭了一天，哭他，也哭自己。</P>
<P class=MsoNormal>哭那个年代。</P>
<P class=MsoNormal>&nbsp;</P>
<P class=MsoNormal>来源：木然</P>
<P class=MsoNormal>链接：<A href="http://dajia.qq.com/blog/184612029854393">http://dajia.qq.com/blog/184612029854393</A></P><br><br>打喷嚏链接：<a href='http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72557' target=_blank>http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72557</a>
<br><br>喷嚏图卦微信：penti_tugua
<br><br><IMG style='BORDER-BOTTOM-COLOR: #000000; BORDER-TOP-COLOR: #000000; BORDER-RIGHT-COLOR: #000000; BORDER-LEFT-COLOR: #000000' border=0 src='http://imgs.dapenti.org:88/dapenti/CcMqMpRg/XY6Yw.jpg'>
<br><br>每天网络精华尽在【<a href='http://www.dapenti.com/blog/blog.asp?subjectid=70&name=xilei' target=_blank>喷嚏图卦</a>】&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='http://weibo.com/dapentizk' title='喷嚏网官方新浪围脖' target='_blank'>喷嚏网官方新浪围脖</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 25 Jan 2013 16:00:00 +0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:6:"author";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72557";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:8;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:2:{s:0:"";a:6:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:24:"【最右】玩玻璃球";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72556";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1661:"<DIV class=WB_info><A class="WB_name S_func3" title=小乔_Beijing href="http://weibo.com/whanw07" node-type="feed_list_originNick" usercard="id=1780086973" nick-name="小乔_Beijing">@小乔_Beijing</A> :06年自主招生语文还有一道题，是写一个四字短语，每个字的偏旁部首都一样，要求每个字都不能重复。我第一反应是魑魅魍魉，可惜一个字都不会写。憋了很久之后写了一个“玩玻璃球”……江河湖海琴瑟琵琶波涛汹涌宜家宜室那么多词……我当时一定是走火入魔憋了一个玩玻璃球。当时觉得北大不可能要我了…… 【最右】<A href="http://weibo.com/n/%E5%8F%AF%E5%AD%90%E5%A3%B3%E5%AD%90%E6%B2%A1%E5%A4%B4%E8%84%91%E5%92%8C%E4%B8%8D%E9%AB%98%E5%85%B4" usercard="name=可子壳子没头脑和不高兴" render="ext">@可子壳子没头脑和不高兴</A>: 玩玻璃球,涂润滑油,膀胱肿胀,痔疮疼痛,没法洗澡</DIV><br><br>打喷嚏链接：<a href='http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72556' target=_blank>http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72556</a>
<br><br>喷嚏图卦微信：penti_tugua
<br><br><IMG style='BORDER-BOTTOM-COLOR: #000000; BORDER-TOP-COLOR: #000000; BORDER-RIGHT-COLOR: #000000; BORDER-LEFT-COLOR: #000000' border=0 src='http://imgs.dapenti.org:88/dapenti/CcMqMpRg/XY6Yw.jpg'>
<br><br>每天网络精华尽在【<a href='http://www.dapenti.com/blog/blog.asp?subjectid=70&name=xilei' target=_blank>喷嚏图卦</a>】&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='http://weibo.com/dapentizk' title='喷嚏网官方新浪围脖' target='_blank'>喷嚏网官方新浪围脖</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 25 Jan 2013 15:48:00 +0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:6:"author";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72556";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}i:9;a:6:{s:4:"data";s:0:"";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";s:5:"child";a:2:{s:0:"";a:6:{s:5:"title";a:1:{i:0;a:5:{s:4:"data";s:34:"龚琳娜新神曲:《金箍棒》";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"link";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72555";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:11:"description";a:1:{i:0;a:5:{s:4:"data";s:1309:"<P>继《法海你不懂爱》后，龚丽娜又为孙悟空唱了首《金箍棒》。她说“这首歌难度系数大大超越了《忐忑》，不光是嘴皮子功夫，更需要强大的气场！”歌词如：金箍棒噶棒噶棒噶棒噶棒噶棒噶棒噶棒噶棒…<A href="http://url.cn/DRYu6s"><FONT color=#336666>http://url.cn/DRYu6s</FONT></A></P>
<P><EMBED height=400 type=application/x-shockwave-flash align=middle width=480 src=http://player.youku.com/player.php/sid/XNTA2Mzg3MjIw/v.swf allowFullscreen="true" allowScriptAccess="sameDomain" quality="high"></EMBED> </P><br><br>打喷嚏链接：<a href='http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72555' target=_blank>http://www.dapenti.com/blog/more.asp?name=xilei&amp;id=72555</a>
<br><br>喷嚏图卦微信：penti_tugua
<br><br><IMG style='BORDER-BOTTOM-COLOR: #000000; BORDER-TOP-COLOR: #000000; BORDER-RIGHT-COLOR: #000000; BORDER-LEFT-COLOR: #000000' border=0 src='http://imgs.dapenti.org:88/dapenti/CcMqMpRg/XY6Yw.jpg'>
<br><br>每天网络精华尽在【<a href='http://www.dapenti.com/blog/blog.asp?subjectid=70&name=xilei' target=_blank>喷嚏图卦</a>】&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<a href='http://weibo.com/dapentizk' title='喷嚏网官方新浪围脖' target='_blank'>喷嚏网官方新浪围脖</a>";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:7:"pubDate";a:1:{i:0;a:5:{s:4:"data";s:31:"Fri, 25 Jan 2013 15:42:00 +0800";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:6:"author";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}s:4:"guid";a:1:{i:0;a:5:{s:4:"data";s:56:"http://www.dapenti.com/blog/more.asp?name=xilei&id=72555";s:7:"attribs";a:1:{s:0:"";a:1:{s:11:"isPermaLink";s:5:"false";}}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}s:32:"http://purl.org/dc/elements/1.1/";a:1:{s:7:"creator";a:1:{i:0;a:5:{s:4:"data";s:5:"xilei";s:7:"attribs";a:0:{}s:8:"xml_base";s:0:"";s:17:"xml_base_explicit";b:0;s:8:"xml_lang";s:0:"";}}}}}}}}}}}}}}}}s:4:"type";i:128;s:7:"headers";a:13:{s:4:"date";s:29:"Fri, 25 Jan 2013 13:27:29 GMT";s:6:"server";s:29:"Apache/2.2.3 (Unix) PHP/5.2.0";s:12:"x-powered-by";s:9:"PHP/5.2.0";s:7:"expires";s:29:"Fri, 25 Jan 2013 13:37:29 GMT";s:13:"cache-control";s:11:"max-age=600";s:13:"last-modified";s:29:"Fri, 25 Jan 2013 12:58:00 GMT";s:4:"etag";s:34:""d41ef159e2423db5c2b922cd8b0ad465"";s:16:"content-encoding";s:4:"gzip";s:4:"vary";s:15:"Accept-Encoding";s:12:"content-type";s:30:"application/xml; charset=utf-8";s:7:"x-cache";s:27:"MISS from squid.feedsky.com";s:14:"x-cache-lookup";s:30:"MISS from squid.feedsky.com:80";s:10:"connection";s:5:"close";}s:5:"build";s:14:"20121030175911";}